title:              newgamedev's blog
tagline:            newgamedev
description:        newgamedev's blog
url:                http://newgamedev.github.io

author:
  name:             newgamedev
  url:
  email:

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
paginate-path:      "/page:lang/page:num/"
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

plugins:
    - jekyll-feed
